### ISSUE TITLE
How I can set a callback to upload / download functions?

### ISSUE THREAD

**Issue by themelisx** [CloudRail/cloudrail-si-java-sdk#8]
Is it possible to set a callback at upload / download functions?
How I know if the operation completed ok?
When I try to download the file (e.g. DropBox) I need a callback that will inform me that the InputStream is ready to be written

**Comment by PatrickStoklasa** [comment]
All of our methods are synchronous since we don't want to interfere with the way you manage threads within your application. This being said, there are no callbacks but they are not needed. In case of an error, the called function will just throw an exception and if it doesn't you can assume that the operation has finished successfully and the data is available. Hope this brings some clarity.

**Comment by themelisx** [comment]
Yes, this is clear! Thank you
